# Generated by Django 3.0.7 on 2020-06-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_sketcher', '0004_auto_20200614_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type_of_paper',
            field=models.DateField(blank=True, choices=[('Proposal Paper', 'Proposal Paper'), ('Research Paper', 'Research Paper'), ('Thesis Paper', 'Thesis Paper')], max_length=500),
        ),
    ]
