# Generated by Django 3.0.3 on 2020-06-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_sketcher', '0006_auto_20200614_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cs_Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250, null=True)),
                ('title', models.TextField(blank=True, max_length=500)),
                ('table_of_contents', models.TextField(blank=True, max_length=500)),
                ('list_of_figures', models.TextField(blank=True, max_length=500)),
                ('abstract', models.TextField(blank=True, max_length=500)),
                ('introduction', models.TextField(blank=True, max_length=500)),
                ('literature_review', models.TextField(blank=True, max_length=500)),
                ('methodology', models.TextField(blank=True, max_length=500)),
                ('plan', models.TextField(blank=True, max_length=500)),
                ('conclusion', models.TextField(blank=True, max_length=500)),
                ('references', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Cs_Research_Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250, null=True)),
                ('title', models.TextField(blank=True, max_length=500)),
                ('keywords', models.TextField(blank=True, max_length=500)),
                ('abstract', models.TextField(blank=True, max_length=500)),
                ('introduction', models.TextField(blank=True, max_length=500)),
                ('background', models.TextField(blank=True, max_length=500)),
                ('methodology', models.TextField(blank=True, max_length=500)),
                ('results', models.TextField(blank=True, max_length=500)),
                ('evaluation', models.TextField(blank=True, max_length=500)),
                ('conclusion', models.TextField(blank=True, max_length=500)),
                ('acknowledgement', models.TextField(blank=True, max_length=500)),
                ('references', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Cs_Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250, null=True)),
                ('title', models.TextField(blank=True, max_length=500)),
                ('abstract', models.TextField(blank=True, max_length=500)),
                ('introduction', models.TextField(blank=True, max_length=500)),
                ('literature_review', models.TextField(blank=True, max_length=500)),
                ('methodology', models.TextField(blank=True, max_length=500)),
                ('results', models.TextField(blank=True, max_length=500)),
                ('evaluation', models.TextField(blank=True, max_length=500)),
                ('conclusion', models.TextField(blank=True, max_length=500)),
                ('references', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='IS_Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250, null=True)),
                ('title', models.TextField(blank=True, max_length=500)),
                ('abstract', models.TextField(blank=True, max_length=500)),
                ('introduction_and_background', models.TextField(blank=True, max_length=500)),
                ('literature_review', models.TextField(blank=True, max_length=500)),
                ('methodology', models.TextField(blank=True, max_length=500)),
                ('data_analysis', models.TextField(blank=True, max_length=500)),
                ('results_and_discussion', models.TextField(blank=True, max_length=500)),
                ('conclusion', models.TextField(blank=True, max_length=500)),
                ('references', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='IS_Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250, null=True)),
                ('title', models.TextField(blank=True, max_length=500)),
                ('abstract', models.TextField(blank=True, max_length=500)),
                ('introduction', models.TextField(blank=True, max_length=500)),
                ('literature_review', models.TextField(blank=True, max_length=500)),
                ('methodology', models.TextField(blank=True, max_length=500)),
                ('results', models.TextField(blank=True, max_length=500)),
                ('evaluation', models.TextField(blank=True, max_length=500)),
                ('conclusion', models.TextField(blank=True, max_length=500)),
                ('references', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='domain_of_Knowledge',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
