# Generated by Django 3.0.3 on 2020-06-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_sketcher', '0007_auto_20200615_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='IS_Research_Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250, null=True)),
                ('title', models.TextField(blank=True, max_length=500)),
                ('abstract', models.TextField(blank=True, max_length=500)),
                ('introduction_and_background', models.TextField(blank=True, max_length=500)),
                ('literature_review', models.TextField(blank=True, max_length=500)),
                ('methodology', models.TextField(blank=True, max_length=500)),
                ('data_analysis', models.TextField(blank=True, max_length=500)),
                ('results_and_discussion', models.TextField(blank=True, max_length=500)),
                ('conclusion', models.TextField(blank=True, max_length=500)),
                ('references', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='is_proposal',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='is_proposal',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='is_proposal',
            name='data_analysis',
        ),
        migrations.RemoveField(
            model_name='is_proposal',
            name='introduction_and_background',
        ),
        migrations.RemoveField(
            model_name='is_proposal',
            name='results_and_discussion',
        ),
        migrations.AddField(
            model_name='is_proposal',
            name='background',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='is_proposal',
            name='data_analysisprocedures',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='is_proposal',
            name='data_collection',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='is_proposal',
            name='objectives',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='is_proposal',
            name='plan',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='is_proposal',
            name='population_and_sample',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='is_proposal',
            name='primary_objectives',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='is_proposal',
            name='problem_statement',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='is_proposal',
            name='report',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='is_proposal',
            name='research_constructs',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='is_proposal',
            name='research_questions',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='is_proposal',
            name='research_significance',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='is_proposal',
            name='secondary_objectives',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='is_proposal',
            name='theoretical_paradigm',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='is_proposal',
            name='time_frame_budget_considerations',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='is_proposal',
            name='variables_relationship',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
