# Generated by Django 3.0.3 on 2020-06-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_sketcher', '0008_auto_20200615_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='domain_of_Knowledge',
            field=models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Information Systems', 'Information Systems')], max_length=500),
        ),
    ]
